"""Data consumed by the other modules. See README.md for how each is used."""

import re

PATCHES_DIR = "patches"

# Gitignored, like PATCHES_DIR: a local review aid, not repo content.
ACCEPTED_DIR = ".sync-accepted"

# Lives under PATCHES_DIR, prefixed so it cannot collide with a patch path.
REPORTS_DIR = "_reports"

# Noted rather than diffed: a patch inside a patch cannot be applied.
OPAQUE_SUFFIXES = (".patch", ".diff")

# corepkgs path prefix -> nixpkgs path prefix. Longest prefix wins.
PATH_MAPPINGS = {
    # keep-sorted start
    "build-support": "pkgs/build-support",
    "build-support/make-fonts-conf/make-fonts-conf.xsl": "pkgs/development/libraries/fontconfig/make-fonts-conf.xsl",
    "build-support/setup-hooks/add-bin-to-path.sh": "pkgs/by-name/ad/addBinToPathHook/add-bin-to-path.sh",
    "build-support/setup-hooks/auto-patchelf.sh": "pkgs/by-name/au/autoPatchelfHook/auto-patchelf.sh",
    "build-support/setup-hooks/autoreconf.sh": "pkgs/by-name/au/autoreconfHook/autoreconf.sh",
    "build-support/setup-hooks/die.sh": "pkgs/by-name/di/dieHook/die.sh",
    "build-support/setup-hooks/fix-darwin-dylib-names.sh": "pkgs/by-name/fi/fixDarwinDylibNames/fix-darwin-dylib-names.sh",
    "build-support/setup-hooks/gog-unpack.sh": "pkgs/by-name/go/gogUnpackHook/gog-unpack.sh",
    "build-support/setup-hooks/set-java-classpath.sh": "pkgs/by-name/se/setJavaClassPath/set-java-classpath.sh",
    "build-support/setup-hooks/strip-java-archives.sh": "pkgs/by-name/st/stripJavaArchivesHook/strip-java-archives.sh",
    "common-updater": "pkgs/common-updater",
    "default.nix": "pkgs/top-level/default.nix",
    "haskell": "pkgs/development/haskell-modules",
    "pkgs": "pkgs/by-name",
    "pkgs/OVMF": "pkgs/applications/virtualization/OVMF",
    "pkgs/R": "pkgs/by-name/r/R",
    "pkgs/acl": "pkgs/development/libraries/acl",
    "pkgs/arm-trusted-firmware": "pkgs/misc/arm-trusted-firmware",
    "pkgs/automake": "pkgs/development/tools/misc/automake",
    "pkgs/bash": "pkgs/shells/bash",
    "pkgs/binlore": "pkgs/development/tools/analysis/binlore",
    "pkgs/binutils": "pkgs/development/tools/misc/binutils",
    "pkgs/boost": "pkgs/development/libraries/boost",
    "pkgs/buildRubyGem": "pkgs/development/ruby-modules/gem",
    "pkgs/bundlerApp": "pkgs/development/ruby-modules",
    "pkgs/busybox": "pkgs/os-specific/linux/busybox",
    "pkgs/bzip2": "pkgs/tools/compression/bzip2",
    "pkgs/cargo-pgrx": "pkgs/development/tools/rust/cargo-pgrx",
    "pkgs/common-updater-scripts": "pkgs/common-updater",
    "pkgs/crystal": "pkgs/development/compilers/crystal",
    "pkgs/dbus": "pkgs/by-name/ma/makeDBusConf",
    "pkgs/defaultGemConfig": "pkgs/development/ruby-modules/gem-config",
    "pkgs/deno/fetchers.nix": "pkgs/by-name/sp/spacetimedb/fetchers.nix",
    "pkgs/docbook-xsl": "pkgs/data/sgml+xml/stylesheets/xslt/docbook-xsl",
    "pkgs/dotnet": "pkgs/development/compilers/dotnet",
    "pkgs/doxygen/doxmlparser.nix": "pkgs/development/python-modules/doxmlparser/default.nix",
    "pkgs/expect": "pkgs/development/tcl-modules/by-name/ex/expect_5",
    "pkgs/fetchDebianPatch": "pkgs/build-support/fetchdebianpatch",
    "pkgs/fetchYarnDeps": "pkgs/build-support/node/fetch-yarn-deps",
    "pkgs/fetchgit": "pkgs/build-support/fetchgit",
    "pkgs/fetchhg": "pkgs/build-support/fetchhg",
    "pkgs/fetchpatch": "pkgs/build-support/fetchpatch",
    "pkgs/fetchsvn": "pkgs/build-support/fetchsvn",
    "pkgs/fetchurl": "pkgs/build-support/fetchurl",
    "pkgs/fetchzip": "pkgs/build-support/fetchzip",
    "pkgs/file": "pkgs/tools/misc/file",
    "pkgs/findutils": "pkgs/tools/misc/findutils",
    "pkgs/fontconfig": "pkgs/development/libraries/fontconfig",
    "pkgs/formats": "pkgs/pkgs-lib",
    "pkgs/gawk": "pkgs/tools/text/gawk",
    "pkgs/gcc": "pkgs/development/compilers/gcc",
    "pkgs/gcc/patches/14/libsanitizer-fix-with-glibc-2.42.patch": "pkgs/development/compilers/gcc/patches/13/libsanitizer-fix-with-glibc-2.42.patch",
    "pkgs/gettext": "pkgs/development/libraries/gettext",
    "pkgs/glibc": "pkgs/development/libraries/glibc",
    "pkgs/gnome": "pkgs/desktops/gnome",
    "pkgs/gnupg": "pkgs/tools/security/gnupg",
    "pkgs/gobject-introspection": "pkgs/development/libraries/gobject-introspection",
    "pkgs/grep": "pkgs/by-name/gn/gnugrep",
    "pkgs/gtk": "pkgs/by-name/gt/gtk2",
    "pkgs/gtk/patches": "pkgs/by-name/gt/gtk3/patches",
    "pkgs/importNpmLock": "pkgs/build-support/node/import-npm-lock",
    "pkgs/iputils": "pkgs/os-specific/linux/iputils",
    "pkgs/javaPackages/openjdk": "pkgs/development/compilers/openjdk",
    "pkgs/julia": "pkgs/development/compilers/julia",
    "pkgs/kmod": "pkgs/os-specific/linux/kmod",
    "pkgs/libbpf": "pkgs/os-specific/linux/libbpf",
    "pkgs/libidn2": "pkgs/development/libraries/libidn2",
    "pkgs/libinput": "pkgs/development/libraries/libinput",
    "pkgs/libliftoff": "pkgs/development/libraries/libliftoff",
    "pkgs/libunistring": "pkgs/development/libraries/libunistring",
    "pkgs/libva": "pkgs/development/libraries/libva",
    "pkgs/libxcrypt": "pkgs/development/libraries/libxcrypt",
    "pkgs/libxml2": "pkgs/development/libraries/libxml2",
    "pkgs/linux": "pkgs/os-specific/linux",
    "pkgs/linux-support": "pkgs/os-specific/linux",
    "pkgs/linux-support/pkgs": "pkgs/os-specific/linux",
    "pkgs/linux-support/pkgs/chipsec": "pkgs/by-name/ch/chipsec",
    "pkgs/linux-support/pkgs/drbd": "pkgs/by-name/dr/drbd",
    "pkgs/linux-support/pkgs/i7z": "pkgs/by-name/i7/i7z",
    "pkgs/linux-support/pkgs/sgx/sdk/cppmicroservices-no-mtime.patch": "pkgs/os-specific/linux/sgx/psw/cppmicroservices-no-mtime.patch",
    "pkgs/linux-support/pkgs/wpa_supplicant": "pkgs/by-name/wp/wpa_supplicant",
    "pkgs/linux/default.nix": "pkgs/top-level/linux-kernels.nix",
    "pkgs/linux/kernel/kernel-config.nix": "nixos/modules/system/boot/kernel_config.nix",
    "pkgs/linux/pkgs": "pkgs/os-specific/linux",
    "pkgs/llvm": "pkgs/development/compilers/llvm",
    "pkgs/lvm2": "pkgs/os-specific/linux/lvm2",
    "pkgs/m4": "pkgs/by-name/gn/gnum4",
    "pkgs/make": "pkgs/by-name/gn/gnumake",
    "pkgs/maturin": "pkgs/by-name/ma/maturin",
    "pkgs/mdadm/fix-hardcoded-mapdir.patch": "pkgs/by-name/md/mdadm4/fix-hardcoded-mapdir.patch",
    "pkgs/mesa": "pkgs/development/libraries/mesa",
    "pkgs/net-tools": "pkgs/os-specific/linux/net-tools",
    "pkgs/nettle": "pkgs/development/libraries/nettle",
    "pkgs/nftables": "pkgs/os-specific/linux/nftables",
    "pkgs/nginx": "pkgs/servers/http/nginx",
    "pkgs/ngtcp2": "pkgs/development/libraries/ngtcp2",
    "pkgs/nix": "pkgs/tools/package-management/nix",
    "pkgs/nix-prefetch-scripts": "pkgs/tools/package-management/nix-prefetch-scripts",
    "pkgs/openblas": "pkgs/development/libraries/science/math/openblas",
    "pkgs/openssh": "pkgs/tools/networking/openssh",
    "pkgs/patch": "pkgs/by-name/gn/gnupatch",
    "pkgs/patchelf": "pkgs/development/tools/misc/patchelf",
    "pkgs/patchutils": "pkgs/tools/text/patchutils",
    "pkgs/perl": "pkgs/development/interpreters/perl",
    "pkgs/pnpmFixupStateDb": "pkgs/by-name/pn/pnpm-fixup-state-db",
    "pkgs/poppler": "pkgs/development/libraries/poppler",
    "pkgs/postgresql": "pkgs/servers/sql/postgresql",
    "pkgs/prefetchNpmDeps": "pkgs/build-support/node/prefetch-npm-deps",
    "pkgs/procps-ng": "pkgs/os-specific/linux/procps-ng",
    "pkgs/readline": "pkgs/development/libraries/readline",
    "pkgs/rpm": "pkgs/tools/package-management/rpm",
    "pkgs/rust": "pkgs/development/compilers/rust",
    "pkgs/rust-bindgen/wrapper.sh": "pkgs/development/tools/rust/bindgen/wrapper.sh",
    "pkgs/rustup": "pkgs/development/tools/rust/rustup",
    "pkgs/rustup-toolchain-install-master": "pkgs/development/tools/rust/rustup-toolchain-install-master",
    "pkgs/sed": "pkgs/tools/text/gnused",
    "pkgs/silver-searcher/bash-completion.patch": "pkgs/by-name/si/silver-searcher-ng/bash-completion.patch",
    "pkgs/sqlite": "pkgs/development/libraries/sqlite",
    "pkgs/substitute": "pkgs/build-support/substitute",
    "pkgs/subversion": "pkgs/applications/version-management/subversion",
    "pkgs/system-sendmail": "pkgs/servers/mail/system-sendmail",
    "pkgs/systemd": "pkgs/os-specific/linux/systemd",
    "pkgs/tar": "pkgs/by-name/gn/gnutar",
    "pkgs/tpm2-tss": "pkgs/development/libraries/tpm2-tss",
    "pkgs/treefmt/modules/default.nix": "pkgs/by-name/tr/treefmt/modules/default.nix",
    "pkgs/uboot": "pkgs/misc/uboot",
    "pkgs/vala": "pkgs/development/compilers/vala",
    "pkgs/xorg": "pkgs/servers/x11/xorg",
    "pkgs/zig": "pkgs/development/compilers/zig",
    "pkgs/zstd": "pkgs/tools/compression/zstd",
    "python": "pkgs/development/interpreters/python",
    "python/cpython/2.7": "pkgs/development/misc/resholve/cpython-2.7",
    "python/cpython/3.7/no-win64-workaround.patch": "pkgs/development/misc/resholve/cpython-2.7/no-win64-workaround.patch",
    "python/hooks/setuptools-rust-hook.sh": "pkgs/development/python-modules/setuptools-rust/setuptools-rust-hook.sh",
    "python/pkgs": "pkgs/development/python-modules",
    "python/pkgs/setuptools": "pkgs/development/misc/resholve/python2-modules/setuptools",
    "python/python2": "pkgs/development/misc/resholve/python2",
    "stdenv": "pkgs/stdenv",
    "stdenv/config.nix": "pkgs/top-level/config.nix",
    "stdenv/generic/meta-types.nix": "lib/meta-types.nix",
    "stdenv/minimal-bootstrap": "pkgs/os-specific/linux/minimal-bootstrap",
    "stdenv/minimal-bootstrap/grep": "pkgs/os-specific/linux/minimal-bootstrap/gnugrep",
    "stdenv/minimal-bootstrap/m4": "pkgs/os-specific/linux/minimal-bootstrap/gnum4",
    "stdenv/minimal-bootstrap/make": "pkgs/os-specific/linux/minimal-bootstrap/gnumake",
    "stdenv/minimal-bootstrap/patch": "pkgs/os-specific/linux/minimal-bootstrap/gnupatch",
    "stdenv/minimal-bootstrap/sed": "pkgs/os-specific/linux/minimal-bootstrap/gnused",
    "stdenv/minimal-bootstrap/tar": "pkgs/os-specific/linux/minimal-bootstrap/gnutar",
    "stdenv/release/lib.nix": "pkgs/top-level/release-lib.nix",
    "stdenv/splice.nix": "pkgs/top-level/splice.nix",
    "stdenv/stage.nix": "pkgs/top-level/stage.nix",
    "stdenv/variants.nix": "pkgs/top-level/variants.nix",
    "unixtools.nix": "pkgs/top-level/unixtools.nix",
    # keep-sorted end
}

# Two-letter shard directories holding `package.nix` rather than `default.nix`.
BY_NAME_PREFIX = "pkgs/by-name"

# Applied to nixpkgs content in order, so specific entries precede general ones.
PATH_REWRITES = [
    (r"\.\./development/perl-modules/generic", "./buildPerlPackage.nix"),
    (r"\.\./development/perl-modules/([^/]+\.patch)", r"./patches/\1"),
    (r"\.\./development/perl-modules", "./patches"),
    (r"\.\./os-specific/linux/", "./"),
    # corepkgs' lib is one file, nixpkgs' a directory.
    (r"((?:\.\./)+)lib(?![\w/.-])", r"\1lib.nix"),
]

# Read at run time, so the vocabulary cannot drift from the real aliases.
ALIAS_FILES = (
    "stdenv/aliases.nix",
    "python/aliases.nix",
)

# Measured against every paired file: rewriting these added more diff than it removed.
ALIAS_EXCLUSIONS = {
    "SDL",  # nixpkgs aliases it too, so both trees already write SDL
    "SDL2",  # nixpkgs aliases it too
    "clj",  # nixpkgs aliases it too
    "man",  # too generic: matches `bintools ? man` and `man unshare` in prose
    "ncurses5",  # nixpkgs aliases it too
    "r",  # too generic: matches `jq -r` and `-r | --relocatable`
    "su",  # nixpkgs aliases it too
    "xxHash",  # nixpkgs aliases it too
}

# Renames no `aliases.nix` entry can express. Applied after the alias-derived ones.
EXTRA_VOCABULARY = [
    (r"\bdocbook_xsl\b", "docbook-xsl-nons"),
    (r"\bdocbook_xsl_ns\b", "docbook-xsl-ns"),
    (r"\bgnumakeBoot\b", "makeBoot"),
    (r"\bgnutarBoot\b", "tarBoot"),
    (r"\blibX11\b", "libx11"),
    (r"\bnixpkgsArgs\b", "pkgsArgs"),
]

# Dropped from incoming nixpkgs content; corepkgs carries none of them.
DROPPED_META_BINDINGS = (
    "crossMaintainers",
    "maintainers",
    "nonTeamMaintainers",
    "teams",
)

# Directories never compared, relative to the corepkgs root.
IGNORE_DIRS = [
    # keep-sorted start
    ".github",
    "ci",  # corepkgs' own evaluation jobs
    "config",
    "dev-shell",  # corepkgs-only
    "docs",
    "ekaos",
    "examples",
    "integration-tests",
    "patches",  # generated by this tool
    "perl",  # too many changes, update manually
    "pkgs-many",
    "pkgs/lndir",  # our minimal implementation
    "pkgs/texlive",  # generated set; upstream at pkgs/tools/typesetting/tex/texlive
    "r",
    "scripts",
    "services",
    "stdenv", # Ported 2026-09-01, except cross cygwin
    # keep-sorted end
]

# Never compared: prose diverges freely and by design.
IGNORE_SUFFIXES = (".md",)

# Individual files never compared, matched as exact paths from the corepkgs root.
IGNORE_FILES = [
    ".gitignore",
    "LICENSE",
    "flake.lock",
    "flake.nix",
    "haskell/hackage-packages.nix",  # generated from Hackage; diffing it is noise
    "lib.nix",
    "pins.nix",
    "release.nix",
    "stdenv/aliases.nix",  # we have our own aliases
    "top-level.nix",
]

TRIVIAL_PATTERNS = [
    re.compile(r'^\s*(?P<key>cargoHash|hash|npmDepsHash|outputHash|sha256|sha512|vendorHash)\s*=\s*"[^"]*";\s*(#.*)?$'),
    re.compile(r'^\s*(?P<key>rev|tag|version)\s*=\s*"[^"]*";\s*(#.*)?$'),
]
"""Lines that are only a moved value. Each pattern must expose a `key` group."""

NOISE_BINDINGS = (
    "__structuredAttrs",
    "doCheck",
    "enableParallelBuilding",
    "enableParallelChecking",
    "enableParallelInstalling",
    "identifiers.cpeParts",
    "passthru.tests",
    "strictDeps",
    "updateScript",
)
"""Bindings dropped whole, body included, however many lines they span."""

NOISE_LINE_PATTERNS = [
    re.compile(r"^\s*#"),
    re.compile(r"^\s*$"),
    re.compile(
        r"^\s*(?:gitUpdater|nix-update-script|nixosTests|testers|unstableGitUpdater)\s*,\s*$"
    ),
    re.compile(r"^\s*[\w.]+\.configurePhaseHook\s*$"),
]
"""Lines that are noise wherever they appear."""

NOISE_SUBSTITUTIONS = [
    (re.compile(r"(?:stdenv\.)?buildPlatform[ \t]*!=[ \t]*(?:stdenv\.)?hostPlatform"), "stdenv.isCross"),
    (re.compile(r"(?:stdenv\.)?buildPlatform[ \t]*==[ \t]*(?:stdenv\.)?hostPlatform"), "!stdenv.isCross"),
    (re.compile(r"(?:stdenv\.)?hostPlatform[ \t]*!=[ \t]*(?:stdenv\.)?buildPlatform"), "stdenv.isCross"),
    (re.compile(r"(?:stdenv\.)?hostPlatform[ \t]*==[ \t]*(?:stdenv\.)?buildPlatform"), "!stdenv.isCross"),
    (re.compile(r"\(\s*finalAttrs\s*:\s*"), ""),
    (re.compile(r"\bfinalAttrs\."), ""),
    (re.compile(r"\brec\s+(?=\{)"), ""),
    (re.compile(r"\}[ \t]*\)"), "}"),
]
"""Rewrites reducing two spellings of one thing to a single form, on both sides."""

EQUIVALENT_KEYS = {
    "sha256": "hash",
    "tag": "rev",
}
"""Interchangeable attribute names, mapped alias -> canonical."""

LOCAL_ONLY = [
    # keep-sorted start
    "build-support/bintools-wrapper/darwin-install_name_tool-wrapper.sh",
    "build-support/bintools-wrapper/darwin-strip-wrapper.sh",
    "build-support/build-fhsenv-chroot",
    "build-support/fake-nss",
    "build-support/make-fonts-cache",
    "build-support/make-fonts-conf/default.nix",
    "build-support/r",
    "build-support/remove-references-to/remove-references-to.sh",
    "build-support/setup-hooks/cygwin-dll-link.sh",
    "build-support/setup-hooks/generate-ld-cache.sh",
    "build-support/setup-hooks/shorten-perl-shebang.sh",
    "build-support/substitute-all",
    "build-support/test-hooks",
    "build-support/testers/pkg-config",
    "pkgs/amd-microcode",
    "pkgs/attr",
    "pkgs/binutils/CVE-2025-5244.diff",
    "pkgs/binutils/CVE-2025-5245.diff",
    "pkgs/buildEnv",
    "pkgs/bundlerApp/default.nix",
    "pkgs/bundlerUpdateScript",
    "pkgs/busybox-sandbox-shell",
    "pkgs/common-updater-scripts/default.nix",
    "pkgs/coreutils/cp-1.patch",
    "pkgs/coreutils/cp-2.patch",
    "pkgs/coreutils/cp-3.patch",
    "pkgs/coreutils/tail.patch",
    "pkgs/dbus/implement-getgrouplist.patch",
    "pkgs/dbus/make-dbus-conf.nix",
    "pkgs/dejavu_fonts",
    "pkgs/deno/librusty_v8.nix",
    "pkgs/deno/tests/default.nix",
    "pkgs/deno/update",
    "pkgs/docbook-sgml-dtd",
    "pkgs/expect/default.nix",
    "pkgs/fetchCrate",
    "pkgs/fetchFromBitbucket",
    "pkgs/fetchFromCodeberg",
    "pkgs/fetchFromGitHub",
    "pkgs/fetchFromGitLab",
    "pkgs/fetchFromGitea",
    "pkgs/fetchFromGitiles",
    "pkgs/fetchFromSavannah",
    "pkgs/fetchFromSourcehut",
    "pkgs/fetchNpmDeps",
    "pkgs/fetchPnpmDeps",
    "pkgs/fetchPypi",
    "pkgs/fetchurl/bootstrap.nix",
    "pkgs/file/32-bit-time_t.patch",
    "pkgs/gcc/libgcc",
    "pkgs/gcc/ng/common/libbacktrace",
    "pkgs/gcc/patches/14/gnat-darwin-dylib-install-name-14.patch",
    "pkgs/gcc/patches/cfi_startproc-reorder-label-2.diff",
    "pkgs/gcc/patches/gnat-darwin-dylib-install-name-13.patch",
    "pkgs/gdk-pixbuf/xlib.nix",
    "pkgs/gettext/memory-safety.patch",
    "pkgs/giflib/CVE-2021-40633.patch",
    "pkgs/giflib/CVE-2025-31344.patch",
    "pkgs/git/update.sh",
    "pkgs/glib/darwin-compilation.patch",
    "pkgs/glibc/ldcache.patch",
    "pkgs/glibc/libgcc-for-glibc.nix",
    "pkgs/gnome/update-script.nix",
    "pkgs/gnupg/default.nix",
    "pkgs/gobject-introspection/unwrapped.nix",
    "pkgs/graphite2",
    "pkgs/gtk-doc/respect-xml-catalog-files-var.patch",
    "pkgs/gtk/3.x.nix",
    "pkgs/gtk/4.x.nix",
    "pkgs/gzip",
    "pkgs/imagemagick/6.x.nix",
    "pkgs/intel-microcode",
    "pkgs/jq/musl.patch",
    "pkgs/ld64/patches/0004-Removed-unused-Blob-clone-method.patch",
    "pkgs/libbpf/sync-uapi-move-constants-from-linux-kernel-h-to-linux-const-h.patch",
    "pkgs/libffi",
    "pkgs/libsoup_3",
    "pkgs/libunwind",
    "pkgs/libxkbcommon",
    "pkgs/libxml2/CVE-2025-6021.patch",
    "pkgs/libxml2/CVE-2025-6170.patch",
    "pkgs/linux-support/default.nix",
    "pkgs/linux-support/kernel/export-rt-sched-migrate.patch",
    "pkgs/linux-support/kernel/hardened",
    "pkgs/linux-support/kernel/kernel-config.nix",
    "pkgs/linux-support/kernel/mptcp-config.nix",
    "pkgs/linux-support/kernel/rt",
    "pkgs/linux-support/pkgs/cpupower-gui",
    "pkgs/linux-support/pkgs/device-tree/raspberrypi.nix",
    "pkgs/linux-support/pkgs/drbd/utils.nix",
    "pkgs/linux-support/pkgs/e1000e",
    "pkgs/linux-support/pkgs/ffado",
    "pkgs/linux-support/pkgs/firmware/ath9k/urls-and-hashes-unstable-2022-05-22.nix",
    "pkgs/linux-support/pkgs/firmware/raspberrypi",
    "pkgs/linux-support/pkgs/freeipa",
    "pkgs/linux-support/pkgs/fwts/module.nix",
    "pkgs/linux-support/pkgs/iptables",
    "pkgs/linux-support/pkgs/lenovo-legion/app.nix",
    "pkgs/linux-support/pkgs/libbpf/sync-uapi-move-constants-from-linux-kernel-h-to-linux-const-h.patch",
    "pkgs/linux-support/pkgs/lvm2/fix-manpage-reproducibility.patch",
    "pkgs/linux-support/pkgs/nullfs",
    "pkgs/linux-support/pkgs/nvidia-x11/open.nix",
    "pkgs/linux-support/pkgs/projecteur",
    "pkgs/linux-support/pkgs/rtl8821ce",
    "pkgs/linux-support/pkgs/sgx/samples",
    "pkgs/linux-support/pkgs/sgx/sdk/default.nix",
    "pkgs/linux-support/pkgs/sgx/sdk/disable-downloads.patch",
    "pkgs/linux-support/pkgs/sgx/sdk/ipp-crypto.nix",
    "pkgs/linux-support/pkgs/sinit",
    "pkgs/linux-support/pkgs/sssd",
    "pkgs/linux-support/pkgs/systemd/0001-Start-device-units-for-uninitialised-encrypted-devic.patch",
    "pkgs/linux-support/pkgs/systemd/0002-Don-t-try-to-unmount-nix-or-nix-store.patch",
    "pkgs/linux-support/pkgs/systemd/0003-Fix-NixOS-containers.patch",
    "pkgs/linux-support/pkgs/systemd/0004-Add-some-NixOS-specific-unit-directories.patch",
    "pkgs/linux-support/pkgs/systemd/0005-Get-rid-of-a-useless-message-in-user-sessions.patch",
    "pkgs/linux-support/pkgs/systemd/0006-hostnamed-localed-timedated-disable-methods-that-cha.patch",
    "pkgs/linux-support/pkgs/systemd/0007-Change-usr-share-zoneinfo-to-etc-zoneinfo.patch",
    "pkgs/linux-support/pkgs/systemd/0008-localectl-use-etc-X11-xkb-for-list-x11.patch",
    "pkgs/linux-support/pkgs/systemd/0009-add-rootprefix-to-lookup-dir-paths.patch",
    "pkgs/linux-support/pkgs/systemd/0010-systemd-shutdown-execute-scripts-in-etc-systemd-syst.patch",
    "pkgs/linux-support/pkgs/systemd/0011-systemd-sleep-execute-scripts-in-etc-systemd-system-.patch",
    "pkgs/linux-support/pkgs/systemd/0012-path-util.h-add-placeholder-for-DEFAULT_PATH_NORMAL.patch",
    "pkgs/linux-support/pkgs/systemd/0013-inherit-systemd-environment-when-calling-generators.patch",
    "pkgs/linux-support/pkgs/systemd/0014-core-don-t-taint-on-unmerged-usr.patch",
    "pkgs/linux-support/pkgs/systemd/0015-tpm2_context_init-fix-driver-name-checking.patch",
    "pkgs/linux-support/pkgs/systemd/0016-systemctl-edit-suggest-systemdctl-edit-runtime-on-sy.patch",
    "pkgs/linux-support/pkgs/systemd/0017-meson.build-do-not-create-systemdstatedir.patch",
    "pkgs/linux-support/pkgs/systemd/0018-meson-Don-t-link-ssh-dropins.patch",
    "pkgs/linux-support/pkgs/systemd/0019-install-unit_file_exists_full-follow-symlinks.patch",
    "pkgs/linux-support/pkgs/systemd/0020-timesyncd-disable-NSCD-when-DNSSEC-validation-is-dis.patch",
    "pkgs/linux-support/pkgs/systemd/musl",
    "pkgs/linux-support/pkgs/trace-cmd",
    "pkgs/linux-support/pkgs/wireguard",
    "pkgs/linux-support/pkgs/wpa_supplicant/gui.nix",
    "pkgs/linux-support/pkgs/xp-pen-drivers",
    "pkgs/lvm2/default.nix",
    "pkgs/lvm2/fix-manpage-reproducibility.patch",
    "pkgs/mariadb-connector-c",
    "pkgs/maturin/pyo3-test/default.nix",
    "pkgs/mdadm/default.nix",
    "pkgs/mdadm/no-self-references.patch",
    "pkgs/mesa/musl.patch",
    "pkgs/mkManyVariants",
    "pkgs/mongosh/disable-telemetry.patch",
    "pkgs/musl/stdio-skip-empty-iovec-when-buffering-is-disabled.patch",
    "pkgs/mysql80",
    "pkgs/netcat",
    "pkgs/nginx/default.nix",
    "pkgs/nix-prefetch-cvs",
    "pkgs/nix-prefetch-darcs",
    "pkgs/nix-prefetch-git",
    "pkgs/nix-prefetch-hg",
    "pkgs/nix-prefetch-pijul",
    "pkgs/nix-prefetch-svn",
    "pkgs/nix-update-script",
    "pkgs/nukeReferences",
    "pkgs/openblas/disable-sme-sgemm-kernel.patch",
    "pkgs/openssh/fix_pkcs11_tests.patch",
    "pkgs/pkgconf",
    "pkgs/pnpmConfigHook",
    "pkgs/pth",
    "pkgs/qemu/canokey-qemu-memcpy.patch",
    "pkgs/qemu/canokey-qemu.nix",
    "pkgs/rhash/do-link-so.patch",
    "pkgs/rhash/dont-fail-ln.patch",
    "pkgs/rsync/fix-tests-in-darwin-sandbox.patch",
    "pkgs/rsync/rrsync.nix",
    "pkgs/rust-bindgen/default.nix",
    "pkgs/rust-bindgen/unwrapped.nix",
    "pkgs/sbt/scala-native.nix",
    "pkgs/silver-searcher/default.nix",
    "pkgs/sqldiff",
    "pkgs/sqlite-analyzer",
    "pkgs/sqlite-rsync",
    "pkgs/sqlite/sqlar.nix",
    "pkgs/substitute/default.nix",
    "pkgs/systemtap-unwrapped/systemtap-elaborate-fix-32bit-build.patch",
    "pkgs/tpm2-tss/no-shadow.patch",
    "pkgs/treefmt/modules/default.nix",
    "pkgs/unixODBC",
    "pkgs/updateAutotoolsGnuConfigScriptsHook",
    "pkgs/userspace-rcu",
    "pkgs/wayland-protocols",
    "pkgs/wayland-scanner",
    "pkgs/wolfssl",
    "pkgs/xcbutil",
    "pkgs/xcbutilerrors",
    "pkgs/xcbutilimage",
    "pkgs/xcbutilkeysyms",
    "pkgs/xcbutilrenderutil",
    "pkgs/xcbutilwm",
    "pkgs/xorg",
    "pkgs/zig/setup-hook.nix",
    "pkgs/zip/12-fix-build-with-gcc-14.patch",
    "pkgs/zlib",
    "python/aliases.nix",
    "python/bootstrap",
    "python/cpython/3.10",
    "python/cpython/3.7/python-3.x-distutils-C++.patch",
    "python/cpython/3.8/no-ldconfig.patch",
    "python/cpython/3.9",
    "python/cpython/docs/2.7-html.nix",
    "python/cpython/docs/2.7-pdf-a4.nix",
    "python/cpython/docs/2.7-pdf-letter.nix",
    "python/cpython/docs/2.7-text.nix",
    "python/cpython/docs/3.10-html.nix",
    "python/cpython/docs/3.10-pdf-a4.nix",
    "python/cpython/docs/3.10-pdf-letter.nix",
    "python/cpython/docs/3.10-texinfo.nix",
    "python/cpython/docs/3.10-text.nix",
    "python/hooks/python-output-test-src-hook.sh",
    "python/packages.nix",
    "python/pkgs/iniconfig/version.patch",
    "python/pkgs/installer/python313-compat.patch",
    "python/pkgs/mypy-extensions",
    "python/pkgs/numpy/numpy-distutils-C++.patch",
    "python/pkgs/roman-numerals-py",
    # keep-sorted end
]
"""Paths with no nixpkgs counterpart: "nothing to compare", not "do not compare"."""

# One patch per subdirectory beneath these, so one package reviews as one patch.
GROUPED_DIRS = [
    "build-support",
    "common-updater",
    "os-specific/linux",
    "pkgs",
]
