# nixos-facter hardware auto-configuration
# Reads a machine-generated JSON report and auto-configures
# kernel modules, firmware, boot settings, and networking
{
  lib,
  config,
  ...
}:
{
  imports = [
    ./audio.nix
    ./boot.nix
    ./bluetooth.nix
    ./bluetooth-stack.nix
    ./camera.nix
    ./cpu.nix
    ./disk.nix
    ./fingerprint.nix
    ./firmware.nix
    ./fwupd.nix
    ./gaming.nix
    ./gpu.nix
    ./graphics.nix
    ./keyboard.nix
    ./laptop.nix
    ./networking.nix
    ./nvidia.nix
    ./power.nix
    ./printing.nix
    ./scanner.nix
    ./system.nix
    ./thermal.nix
    ./thunderbolt.nix
    ./touchscreen.nix
    ./trackpoint.nix
    ./virtualisation.nix
  ];

  options.hardware.facter = with lib; {
    enable = mkOption {
      type = types.bool;
      default = config.hardware.facter.report != { };
      defaultText = literalExpression ''
        config.hardware.facter.report != { }
      '';
      description = ''
        Whether to enable automatic hardware configuration using a
        report generated by nixos-facter.

        To generate a report, run as root:
          nix-shell -p nixos-facter --run nixos-facter > facter.json

        Then set hardware.facter.reportPath = ./facter.json in your config.
      '';
    };

    report = mkOption {
      type = types.attrsOf types.anything;
      default =
        if config.hardware.facter.reportPath == null then
          { }
        else
          builtins.fromJSON (builtins.readFile config.hardware.facter.reportPath);
      defaultText = "A JSON import from config.hardware.facter.reportPath (if not null), {} otherwise.";
      description = "Hardware report data generated by nixos-facter.";
    };

    reportPath = mkOption {
      type = types.nullOr types.path;
      default = null;
      description = ''
        Path to a hardware report generated by nixos-facter.

        To generate a report, run the following as root:
          nix-shell -p nixos-facter --run nixos-facter > facter.json
      '';
    };
  };
}
