{
  version,
  src-hash,
  nix-ssl-cert-file-patch ? null,
  kernel-detection-patch ? null,
  use-etc-ssl-certs-patch,
  use-etc-ssl-certs-darwin-patch,
  mingw-linking-patch ? null,
  withDocs ? false,
  extraMeta ? { },
  enableFips ? false,
  needsOQSProvider ? false,
  oqsExtraINIConfig ? null,
  packageAtLeast,
  ...
}@variantArgs:

{
  lib,
  stdenv,
  fetchurl,
  buildPackages,
  perl,
  coreutils,
  writeShellScript,
  makeBinaryWrapper,
  withCryptodev ? false,
  cryptodev ? null,
  withZlib ? false,
  zlib,
  enableSSL2 ? false,
  enableSSL3 ? false,
  enableMD2 ? false,
  enableKTLS ? stdenv.hostPlatform.isLinux,
  # change this to a value between 0 and 5 (as of OpenSSL 3.5)
  # if null, default is used, changes the permitted algorithms
  # and key lengths in the default config
  # see: https://docs.openssl.org/3.5/man3/SSL_CTX_set_security_level/
  securityLevel ? null,
  static ? stdenv.hostPlatform.isStatic,
  # path to openssl.cnf file. will be placed in $etc/etc/ssl/openssl.cnf to replace the default
  conf ? null,
  removeReferencesTo,
  testers,
  oqs-provider ? null,
  providers ? (
    if needsOQSProvider && oqs-provider != null then
      [
        {
          name = "oqsprovider";
          package = oqs-provider;
        }
      ]
    else
      [ ]
  ),
  autoloadProviders ? needsOQSProvider,
  extraINIConfig ? (if oqsExtraINIConfig != null then oqsExtraINIConfig else null),
  runUnitTests,

  # for passthru.tests
  git,
  curl,
  openssh,
}:

# Note: this package is used for bootstrapping fetchurl, and thus
# cannot use fetchpatch! All mutable patches (generated by GitHub or
# cgit) that are needed here should be included directly in Nixpkgs as
# files.

# check from time to time, if this range is still correct
assert (securityLevel == null) || (securityLevel >= 0 && securityLevel <= 5);

stdenv.mkDerivation (finalAttrs: {
  pname = "openssl";
  inherit version;

  src = fetchurl {
    url = "https://github.com/openssl/openssl/releases/download/openssl-${version}/openssl-${version}.tar.gz";
    hash = src-hash;
  };

  patches =
    lib.optional (nix-ssl-cert-file-patch != null) nix-ssl-cert-file-patch
    ++ lib.optional (kernel-detection-patch != null) kernel-detection-patch
    ++ [
      (if stdenv.hostPlatform.isDarwin then use-etc-ssl-certs-darwin-patch else use-etc-ssl-certs-patch)
    ]
    ++ lib.optionals (stdenv.hostPlatform.isMinGW && mingw-linking-patch != null) [
      mingw-linking-patch
    ];

  postPatch = ''
    patchShebangs Configure

    # config is a configure script which is not installed.
    substituteInPlace config --replace '/usr/bin/env' '${buildPackages.coreutils}/bin/env'
  ''
  + lib.optionalString stdenv.hostPlatform.isMusl ''
    substituteInPlace crypto/async/arch/async_posix.h \
      --replace '!defined(__ANDROID__) && !defined(__OpenBSD__)' \
                '!defined(__ANDROID__) && !defined(__OpenBSD__) && 0'
  ''
  # Move ENGINESDIR into OPENSSLDIR for static builds, in order to move
  # it to the separate etc output.
  + lib.optionalString static ''
    substituteInPlace Configurations/unix-Makefile.tmpl \
      --replace 'ENGINESDIR=$(libdir)/engines-{- $sover_dirname -}' \
                'ENGINESDIR=$(OPENSSLDIR)/engines-{- $sover_dirname -}'
  ''
  # This test will fail if the error strings between the build libc and host
  # libc mismatch, e.g. when cross-compiling from glibc to musl
  +
    lib.optionalString
      (finalAttrs.finalPackage.doCheck && stdenv.hostPlatform.libc != stdenv.buildPlatform.libc)
      ''
        rm test/recipes/02-test_errstr.t
      '';

  outputs = [
    "bin"
    "dev"
    "out"
    "man"
  ]
  ++ lib.optional withDocs "doc"
  # Separate output for the runtime dependencies of the static build.
  # Specifically, move OPENSSLDIR into this output, as its path will be
  # compiled into 'libcrypto.a'. This makes it a runtime dependency of
  # any package that statically links openssl, so we want to keep that
  # output minimal.
  ++ lib.optional static "etc";
  setOutputFlags = false;
  separateDebugInfo =
    !stdenv.hostPlatform.isDarwin
    && !stdenv.hostPlatform.isAndroid
    && !(stdenv.hostPlatform.useLLVM or false)
    && stdenv.cc.isGNU;

  nativeBuildInputs =
    lib.optional (!stdenv.hostPlatform.isWindows) makeBinaryWrapper
    ++ [ perl ]
    ++ lib.optionals static [ removeReferencesTo ];
  buildInputs = lib.optional withCryptodev cryptodev ++ lib.optional withZlib zlib;

  # TODO(@Ericson2314): Improve with mass rebuild
  configurePlatforms = [ ];
  configureScript =
    {
      armv5tel-linux = "./Configure linux-armv4 -march=armv5te";
      armv6l-linux = "./Configure linux-armv4 -march=armv6";
      armv7l-linux = "./Configure linux-armv4 -march=armv7-a";
      aarch64-darwin = "./Configure darwin64-arm64-cc";
      x86_64-linux = "./Configure linux-x86_64";
      x86_64-solaris = "./Configure solaris64-x86_64-gcc";
      powerpc-linux = "./Configure linux-ppc";
      powerpc64-linux = "./Configure linux-ppc64";
      riscv32-linux = "./Configure ${
        if packageAtLeast "3.2" then "linux32-riscv32" else "linux-latomic"
      }";
      riscv64-linux = "./Configure linux64-riscv64";
    }
    .${stdenv.hostPlatform.system} or (
      if stdenv.hostPlatform == stdenv.buildPlatform then
        "./config"
      else if stdenv.hostPlatform.isBSD then
        if stdenv.hostPlatform.isx86_64 then
          "./Configure BSD-x86_64"
        else if stdenv.hostPlatform.isx86_32 then
          "./Configure BSD-x86" + lib.optionalString stdenv.hostPlatform.isElf "-elf"
        else
          "./Configure BSD-generic${toString stdenv.hostPlatform.parsed.cpu.bits}"
      else if stdenv.hostPlatform.isMinGW then
        "./Configure mingw${
          lib.optionalString (stdenv.hostPlatform.parsed.cpu.bits != 32) (
            toString stdenv.hostPlatform.parsed.cpu.bits
          )
        }"
      else if stdenv.hostPlatform.isLinux then
        if stdenv.hostPlatform.isx86_64 then
          "./Configure linux-x86_64"
        else if stdenv.hostPlatform.isMicroBlaze then
          "./Configure linux-latomic"
        else if stdenv.hostPlatform.isMips32 then
          "./Configure linux-mips32"
        else if stdenv.hostPlatform.isMips64n32 then
          "./Configure linux-mips64"
        else if stdenv.hostPlatform.isMips64n64 then
          "./Configure linux64-mips64"
        else
          "./Configure linux-generic${toString stdenv.hostPlatform.parsed.cpu.bits}"
      else if stdenv.hostPlatform.isiOS then
        "./Configure ios${toString stdenv.hostPlatform.parsed.cpu.bits}-cross"
      else
        throw "Not sure what configuration to use for ${stdenv.hostPlatform.config}"
    );

  # OpenSSL doesn't like the `--enable-static` / `--disable-shared` flags.
  dontAddStaticConfigureFlags = true;
  configureFlags = [
    "shared" # "shared" builds both shared and static libraries
    "--libdir=lib"
    (
      if !static then
        "--openssldir=etc/ssl"
      else
        # Move OPENSSLDIR to the 'etc' output for static builds. Prepend '/.'
        # to the path to make it appear absolute before variable expansion,
        # else the 'prefix' would be prepended to it.
        "--openssldir=/.$(etc)/etc/ssl"
    )
  ]
  ++ lib.optionals withCryptodev [
    "-DHAVE_CRYPTODEV"
    "-DUSE_CRYPTODEV_DIGESTS"
  ]
  # enable optimized EC curve primitives on x86_64,
  # can provide a 2x up to 4x speedup at best
  # with combined PQC and conventional crypto handshakes
  # starting with 3.5 its nice to speed things up for free
  ++ lib.optional stdenv.hostPlatform.isx86_64 "enable-ec_nistp_64_gcc_128"
  # useful to set e.g. 256 bit security level with setting this to 5
  ++ lib.optional (securityLevel != null) "-DOPENSSL_TLS_SECURITY_LEVEL=${toString securityLevel}"
  ++ lib.optional enableMD2 "enable-md2"
  ++ lib.optional enableSSL2 "enable-ssl2"
  ++ lib.optional enableSSL3 "enable-ssl3"
  ++ lib.optional enableFips "enable-fips"
  # We select KTLS here instead of the configure-time detection (which we patch out).
  # KTLS should work on FreeBSD 13+ as well, so we could enable it if someone tests it.
  ++ lib.optional enableKTLS "enable-ktls"
  ++ lib.optional stdenv.hostPlatform.isAarch64 "no-afalgeng"
  # OpenSSL needs a specific `no-shared` configure flag.
  # See https://wiki.openssl.org/index.php/Compilation_and_Installation#Configure_Options
  # for a comprehensive list of configuration options.
  ++ lib.optionals static [
    "no-shared"
    "no-module"
  ]
  # This introduces a reference to the CTLOG_FILE which is undesired when
  # trying to build binaries statically.
  ++ lib.optional static "no-ct"
  ++ lib.optional withZlib "zlib"
  # /dev/crypto support has been dropped in OpenBSD 5.7.
  #
  # OpenBSD's ports does this too,
  # https://github.com/openbsd/ports/blob/a1147500c76970fea22947648fb92a093a529d7c/security/openssl/3.3/Makefile#L25.
  #
  # https://github.com/openssl/openssl/pull/10565 indicated the
  # intent was that this would be configured properly automatically,
  # but that doesn't appear to be the case.
  ++ lib.optional stdenv.hostPlatform.isOpenBSD "no-devcryptoeng"
  ++ lib.optionals (stdenv.hostPlatform.isMips && stdenv.hostPlatform ? gcc.arch) [
    # This is necessary in order to avoid openssl adding -march
    # flags which ultimately conflict with those added by
    # cc-wrapper.  Openssl assumes that it can scan CFLAGS to
    # detect any -march flags, using this perl code:
    #
    #   && !grep { $_ =~ /-m(ips|arch=)/ } (@{$config{CFLAGS}})
    #
    # The following bogus CFLAGS environment variable triggers the
    # the code above, inhibiting `./Configure` from adding the
    # conflicting flags.
    "CFLAGS=-march=${stdenv.hostPlatform.gcc.arch}"
  ]
  # tests are not being installed, it makes no sense
  # to build them if check is disabled, e.g. on cross.
  ++ lib.optional (!finalAttrs.finalPackage.doCheck) "disable-tests";

  makeFlags = [
    "MANDIR=$(man)/share/man"
    # This avoids conflicts between man pages of openssl subcommands and
    # equivalent top-level commands in other packages (for example 'err'
    # from man-pages).
    # This is done in ubuntu and archlinux, and possibly many other distros.
    "MANSUFFIX=ssl"
  ];

  preCheck = ''
    patchShebangs util
  '';

  __darwinAllowLocalNetworking = true;

  postInstall =
    (
      if static then
        ''
          # OPENSSLDIR has a reference to self
          remove-references-to -t $out $out/lib/*.a
        ''
      else
        ''
          # If we're building dynamic libraries, then don't install static
          # libraries.
          if [ -n "$(echo $out/lib/*.so $out/lib/*.dylib $out/lib/*.dll)" ]; then
              rm "$out/lib/"*.a
          fi

          # 'etc' is a separate output on static builds only.
          etc=$out
        ''
    )
    + ''
      mkdir -p $bin
      mv $out/bin $bin/bin

    ''
    +
      lib.optionalString (!stdenv.hostPlatform.isWindows)
        # makeWrapper is broken for windows cross (https://github.com/NixOS/nixpkgs/issues/120726)
        ''
          # c_rehash is a legacy perl script with the same functionality
          # as `openssl rehash`
          # this wrapper script is created to maintain backwards compatibility without
          # depending on perl
          makeWrapper $bin/bin/openssl $bin/bin/c_rehash \
            --add-flags "rehash"
        ''
    + ''

      mkdir $dev
      mv $out/include $dev/

      # remove dependency on Perl at runtime
      rm -r $etc/etc/ssl/misc

      rmdir $etc/etc/ssl/{certs,private}
    ''
    + lib.optionalString (conf != null) ''
      cat ${conf} > $etc/etc/ssl/openssl.cnf
    ''

    # Replace the config's default provider section with the providers we wish
    # to automatically load
    + lib.optionalString autoloadProviders ''
      sed -i '/^[[:space:]]*#/!s|\[provider_sect\]|${
        let
          config-provider-attrset = lib.foldl' (acc: elem: acc // elem) { } (
            map (provider: { "${provider.name}" = "${provider.name}_sect"; }) providers
          );
        in
        lib.escape [ "\n" ] (lib.generators.toINI { } { provider_sect = config-provider-attrset; })
      }|' $etc/etc/ssl/openssl.cnf

      # Activate the default provider
      sed -i '/^[[:space:]]*#/!s/\[default_sect\]/[default_sect]\nactivate = 1/g' $etc/etc/ssl/openssl.cnf
    ''

    + lib.concatStringsSep "\n" (
      map
        (provider: ''
          cp ${provider.package}/lib/ossl-modules/* "$out/lib/ossl-modules"

          ${lib.optionalString autoloadProviders ''
            echo '${
              lib.generators.toINI { } {
                "${provider.name}_sect" = {
                  activate = 1;
                };
              }
            }' >> $etc/etc/ssl/openssl.cnf
          ''}
        '')

        providers
    )
    + lib.optionalString (extraINIConfig != null) ''
      echo '${lib.generators.toINI { } extraINIConfig}' >> $etc/etc/ssl/openssl.cnf
    ''
    # Add the FIPS and base providers to openssl.cnf. The fips_sect contents
    # (with HMAC) are appended in postFixup after patchelf/strip are done,
    # since those modify fips.so and would invalidate the integrity hash.
    + lib.optionalString enableFips ''
      # Add the FIPS provider to the provider section
      sed -i '/^[[:space:]]*#/!s|\[provider_sect\]|[provider_sect]\nfips = fips_sect|' $etc/etc/ssl/openssl.cnf

      # Activate the default provider (if not already done by autoloadProviders)
      ${lib.optionalString (!autoloadProviders) ''
        sed -i '/^[[:space:]]*#/!s/\[default_sect\]/[default_sect]\nactivate = 1/g' $etc/etc/ssl/openssl.cnf
      ''}

      # Activate the base provider (needed alongside FIPS for non-crypto operations like encoding)
      echo '[base_sect]
      activate = 1' >> $etc/etc/ssl/openssl.cnf
      sed -i '/^[[:space:]]*#/!s|\[provider_sect\]|[provider_sect]\nbase = base_sect|' $etc/etc/ssl/openssl.cnf
    '';

  allowedImpureDLLs = [ "CRYPT32.dll" ];

  postFixup =
    lib.optionalString (!stdenv.hostPlatform.isWindows) ''
      # Check to make sure the main output and the static runtime dependencies
      # don't depend on perl
      if grep -r '${buildPackages.perl}' $out $etc; then
        echo "Found an erroneous dependency on perl ^^^" >&2
        exit 1
      fi
    ''
    + lib.optionalString (packageAtLeast "3.3.0") ''
      # cleanup cmake helpers for now (for OpenSSL >= 3.3), only rely on pkg-config.
      # pkg-config gets its paths fixed correctly
      rm -rf $dev/lib/cmake
    ''
    # Run fipsinstall after all fixup (patchelf, strip) is complete so the
    # HMAC integrity hash matches the final fips.so binary. Inline the
    # generated fips_sect into openssl.cnf (OpenSSL's .include directive
    # does not reliably merge sections from included files).
    # Use OPENSSL_CONF=/dev/null to prevent the openssl binary from loading
    # the config (which references fips_sect before it exists).
    + lib.optionalString enableFips ''
      OPENSSL_CONF=/dev/null $bin/bin/openssl fipsinstall \
        -out $etc/etc/ssl/fipsmodule.cnf \
        -module $out/lib/ossl-modules/fips.so
      cat $etc/etc/ssl/fipsmodule.cnf >> $etc/etc/ssl/openssl.cnf
    '';

  passthru = {
    tests = {
      pkg-config = testers.testMetaPkgConfig finalAttrs.finalPackage;
      pkg-config-install = testers.pkg-config.testInstall finalAttrs.finalPackage { };
      unittests = runUnitTests finalAttrs.finalPackage;
      inherit git curl openssh;
    };
  };

  meta = {
    homepage = "https://www.openssl.org/";
    changelog = "https://github.com/openssl/openssl/blob/openssl-${version}/CHANGES.md";
    description = "Cryptographic library that implements the SSL and TLS protocols";
    license = lib.licenses.openssl;
    mainProgram = "openssl";

    pkgConfigModules = [
      "libcrypto"
      "libssl"
      "openssl"
    ];
    platforms = lib.platforms.all;
    identifiers.cpeParts = lib.meta.cpeFullVersionWithVendor "openssl" finalAttrs.version;
  }
  // extraMeta;
})
