{
  version,
  sha256,
  packageAtLeast,
  packageOlder,
  mkVariantPassthru,
  ...
}@variantArgs:

{
  stdenv,
  fetchurl,
  fetchFromGitHub,
  buildPackages,
  lib,
  callPackage,
  pkgsBuildBuild,
  pkgsBuildHost,
  pkgsBuildTarget,
  pkgsHostHost,
  pkgsTargetTarget,
  zlib,
  config,
  enableThreading ? true,
  coreutils,
  makeWrapper,
  enableCrypt ? true,
  libxcrypt ? null,
  self ? null,
  overrides ? config.perlPackageOverrides or (p: { }), # TODO: (self: super: {}) like in python
}@inputs:

# Note: this package is used for bootstrapping fetchurl, and thus
# cannot use fetchpatch! All mutable patches (generated by GitHub or
# cgit) that are needed here should be included directly in Nixpkgs as
# files.

assert (enableCrypt -> (libxcrypt != null));

let
  crossCompiling = !(stdenv.buildPlatform.canExecute stdenv.hostPlatform);

  # ./patches/common holds the patches that are the same file for every
  # version; ./patches/<major>.<minor> the ones rebased per release.
  versionPatches = ./patches + "/${lib.versions.majorMinor version}";

  commonPatches = [
    # Do not look in /usr etc. for dependencies.
    (versionPatches + "/no-sys-dirs.patch")

    # Super-linear cache overflow in the regex engine.
    ./patches/common/CVE-2026-15534-1.patch
    ./patches/common/CVE-2026-15534-2.patch
  ]

  # Both fixed upstream in 5.42.0.
  ++ lib.optionals (lib.versionOlder version "5.42.0") [
    (versionPatches + "/CVE-2024-56406.patch")
    (versionPatches + "/CVE-2025-40909.patch")
  ]

  # Build fix for a C-only locale: https://github.com/Perl/perl5/pull/22569
  ++ lib.optional (version == "5.40.0") (versionPatches + "/fix-build-with-only-C-locale.patch")

  # Build fix for Solaris on x86_64: https://github.com/Perl/perl5/issues/9669
  ++ lib.optional stdenv.hostPlatform.isSunOS ./patches/common/ld-shared.patch

  # Stop passing -no-cpp-precomp: obsolete since ~2002, but clang still takes it.
  ++ lib.optional stdenv.hostPlatform.isDarwin ./patches/common/cpp-precomp.patch

  # hints/darwin.sh shells out to sw_vers, which the sandbox lacks. Fixed
  # upstream in 5.42.0, where this patch also no longer applies.
  ++ lib.optional (stdenv.hostPlatform.isDarwin && lib.versionOlder version "5.42.0") (
    versionPatches + "/sw_vers.patch"
  )

  # Let miniperl load more modules, which cross bootstrapping needs:
  # https://arsv.github.io/perl-cross/modules.html
  ++ lib.optional crossCompiling (versionPatches + "/cross.patch");

  libc = if stdenv.cc.libc or null != null then stdenv.cc.libc else "/usr";
  libcInc = lib.getDev libc;
  libcLib = lib.getLib libc;

  # Compute the variant attribute from version (e.g. "5.38.2" -> "v5_38").
  # Selecting the variant directly keeps this independent of the `perl538`
  # style aliases, which are gone when `config.aliases.nixpkgs` is false.
  perlVariant = "v${lib.versions.major version}_${lib.versions.minor version}";

  # Common passthru function for perl interpreters
  # Adapted from the original passthruFun in pkgs/perl/default.nix
  passthruFun =
    {
      perlOnBuildForBuild,
      perlOnBuildForHost,
      perlOnBuildForTarget,
      perlOnHostForHost,
      perlOnTargetForTarget,
      tests ? { },
      self, # is perlOnHostForTarget
    }:
    let
      perlPackages =
        callPackage
          # Function that when called
          # - imports perl-packages.nix
          # - adds spliced package sets to the package set
          (
            {
              perl,
              callPackage,
              makeScopeWithSplicing',
            }:
            let
              # One directory per package under perl/pkgs, auto-called from this
              # scope so each expression declares its dependencies as arguments.
              autoCalledOverlay = lib.packageSets.mkAutoCalledPackageDir ../../perl/pkgs;

              perlPackagesFun = callPackage ../../perl/perl-packages.nix {
                perl = self;
              };

              otherSplices = {
                selfBuildBuild = perlOnBuildForBuild.pkgs;
                selfBuildHost = perlOnBuildForHost.pkgs;
                selfBuildTarget = perlOnBuildForTarget.pkgs;
                selfHostHost = perlOnHostForHost.pkgs;
                selfTargetTarget = perlOnTargetForTarget.pkgs or { };
              };
            in
            makeScopeWithSplicing' {
              inherit otherSplices;
              f = lib.extends autoCalledOverlay perlPackagesFun;
            }
          )
          {
            perl = self;
          };
    in
    rec {
      buildEnv = callPackage ./wrapper.nix {
        perl = self;
        inherit (pkgs) requiredPerlModules;
      };
      withPackages = f: buildEnv.override { extraLibs = f pkgs; };
      pkgs = perlPackages // (overrides pkgs);
      interpreter = "${self}/bin/perl";
      libPrefix = "lib/perl5/site_perl";
      perlOnBuild = perlOnBuildForHost.override {
        inherit overrides;
        self = perlOnBuild;
      };

      inherit tests;
    };

  # We need a recursive binding for self-reference in passthru
  self = stdenv.mkDerivation (
    finalAttrs:
    {
      inherit version;
      pname = "perl";

      src = fetchurl {
        url = "mirror://cpan/src/5.0/perl-${version}.tar.gz";
        inherit sha256;
      };

      # TODO: Add a "dev" output containing the header files.
      outputs = [
        "out"
        "man"
        "devdoc"
      ]
      ++ lib.optional crossCompiling "mini";
      setOutputFlags = false;

      # On FreeBSD, if Perl is built with threads support, having
      # libxcrypt available will result in a build failure, because
      # perl.h will get conflicting definitions of struct crypt_data
      # from libc's unistd.h and libxcrypt's crypt.h.
      #
      # FreeBSD Ports has the same issue building the perl port if
      # the libxcrypt port has been installed.
      #
      # Without libxcrypt, Perl will still find FreeBSD's crypt functions.
      propagatedBuildInputs = lib.optional (enableCrypt && !stdenv.hostPlatform.isFreeBSD) libxcrypt;

      disallowedReferences = [ stdenv.cc ];

      patches = commonPatches;

      # This is not done for native builds because pwd may need to come from
      # bootstrap tools when building bootstrap perl.
      postPatch =
        (
          if crossCompiling then
            ''
              substituteInPlace dist/PathTools/Cwd.pm \
                --replace "/bin/pwd" '${coreutils}/bin/pwd'
              substituteInPlace cnf/configure_tool.sh --replace "cc -E -P" "cc -E"
            ''
          else
            ''
              substituteInPlace dist/PathTools/Cwd.pm \
                --replace "/bin/pwd" "$(type -P pwd)"
            ''
        )
        +
        # Perl's build system uses the src variable, and its value may end up in
        # the output in some cases (when cross-compiling).
        ''
          unset src
        '';

      # Build a thread-safe Perl with a dynamic libperl.so.  We need the
      # "installstyle" option to ensure that modules are put under
      # $out/lib/perl5 - this is the general default, but because $out
      # contains the string "perl", Configure would select $out/lib.
      # Miniperl needs -lm. perl needs -lrt.
      configureFlags =
        (
          if crossCompiling then
            [
              "-Dlibpth=\"\""
              "-Dglibpth=\"\""
              "-Ddefault_inc_excludes_dot"
              # https://github.com/arsv/perl-cross/issues/158
              "-Dd_gnulibc=define"
            ]
          else
            (
              [
                "-de"
                "-Dprefix=${placeholder "out"}"
                "-Dman1dir=${placeholder "out"}/share/man/man1"
                "-Dman3dir=${placeholder "out"}/share/man/man3"
              ]
              ++ (
                if (stdenv.cc.targetPrefix != "") then
                  [
                    "-Dcc=${stdenv.cc.targetPrefix}cc"
                    "-Dnm=${stdenv.cc.targetPrefix}nm"
                    "-Dar=${stdenv.cc.targetPrefix}ar"
                  ]
                else
                  [
                    "-Dcc=cc"
                    "-Duseshrplib"
                  ]
              )
            )
        )
        ++ [
          "-Uinstallusrbinperl"
          "-Dinstallstyle=lib/perl5"
          "-Dlocincpth=${libcInc}/include"
          "-Dloclibpth=${libcLib}/lib"
          "-Accflags=-D_GNU_SOURCE"
        ]
        ++ lib.optional stdenv.hostPlatform.isStatic "-Uusedl"
        ++ lib.optionals ((builtins.match ''5\.[0-9]*[13579]\..+'' version) != null) [
          "-Dusedevel"
          "-Uversiononly"
        ]
        ++ lib.optional stdenv.hostPlatform.isSunOS "-Dcc=gcc"
        ++ lib.optional enableThreading "-Dusethreads"
        ++ lib.optional (!enableCrypt) "-A clear:d_crypt_r"
        ++ lib.optionals (stdenv.hostPlatform.isFreeBSD && crossCompiling && enableCrypt) [
          # https://github.com/Perl/perl5/issues/22295
          # configure cannot figure out that we have crypt automatically, but we really do
          "-Dd_crypt"
        ];

      configureScript = lib.optionalString (!crossCompiling) "${stdenv.shell} ./Configure";

      # !canExecute cross uses miniperl which doesn't have this
      postConfigure =
        lib.optionalString (!crossCompiling && stdenv.cc.targetPrefix != "") ''
          substituteInPlace Makefile \
            --replace-fail "AR = ar" "AR = ${stdenv.cc.targetPrefix}ar"
        ''
        + lib.optionalString crossCompiling ''
          substituteInPlace miniperl_top --replace-fail '-I$top/lib' '-I$top/cpan/JSON-PP/lib -I$top/cpan/CPAN-Meta-YAML/lib -I$top/lib'
        '';

      dontAddStaticConfigureFlags = true;

      dontAddPrefix = !crossCompiling;

      # perl includes the build date, the uname of the build system and the
      # username of the build user in some files.
      # We override these to make it build deterministically.
      # other distro solutions
      # https://github.com/bmwiedemann/openSUSE/blob/master/packages/p/perl/perl-reproducible.patch
      # https://github.com/archlinux/svntogit-packages/blob/packages/perl/trunk/config.over
      # https://salsa.debian.org/perl-team/interpreter/perl/blob/debian-5.26/debian/config.over
      # A ticket has been opened upstream to possibly clean some of this up: https://rt.perl.org/Public/Bug/Display.html?id=133452
      preConfigure = ''
        cat > config.over <<EOF
        ${lib.optionalString (
          stdenv.hostPlatform.isLinux && stdenv.hostPlatform.isGnu
        ) ''osvers="gnulinux"''}
        myuname="nixpkgs"
        myhostname="nixpkgs"
        cf_by="nixpkgs"
        cf_time="$(date -d "@$SOURCE_DATE_EPOCH")"
        EOF

        # Compress::Raw::Zlib should use our zlib package instead of the one
        # included with the distribution
        cat > ./cpan/Compress-Raw-Zlib/config.in <<EOF
        BUILD_ZLIB   = False
        INCLUDE      = ${zlib.dev}/include
        LIB          = ${zlib.out}/lib
        OLD_ZLIB     = False
        GZIP_OS_CODE = AUTO_DETECT
        USE_ZLIB_NG  = False
      ''
      + lib.optionalString (lib.versionAtLeast version "5.40.0") ''
        ZLIB_INCLUDE = ${zlib.dev}/include
        ZLIB_LIB     = ${zlib.out}/lib
      ''
      + ''
        EOF
      ''
      + lib.optionalString stdenv.hostPlatform.isDarwin ''
        substituteInPlace hints/darwin.sh --replace "env MACOSX_DEPLOYMENT_TARGET=10.3" ""
      ''
      + lib.optionalString (!enableThreading) ''
        # We need to do this because the bootstrap doesn't have a static libpthread
        sed -i 's,\(libswanted.*\)pthread,\1,g' Configure
      '';

      # Default perl does not support --host= & co.
      configurePlatforms = [ ];

      setupHook = ./setup-hook.sh;

      env = {
        # https://github.com/llvm/llvm-project/issues/152241
        NIX_CFLAGS_COMPILE = lib.optionalString (
          stdenv.hasCC && stdenv.cc.isClang && lib.versionAtLeast stdenv.cc.version "21"
        ) "-fno-strict-aliasing";
      };

      # copied from python
      passthru =
        let
          # When we override the interpreter we also need to override the spliced versions of the interpreter
          inputs' = lib.filterAttrs (n: v: !lib.isDerivation v) inputs;
          override =
            attr:
            let
              perl = attr.override inputs';
            in
            perl;
        in
        mkVariantPassthru variantArgs
        // {
          ekapkgs-update.semver-strategy = "patch";
        }
        // passthruFun {
          inherit self;
          perlOnBuildForBuild = override pkgsBuildBuild.perl.${perlVariant};
          perlOnBuildForHost = override pkgsBuildHost.perl.${perlVariant};
          perlOnBuildForTarget = override pkgsBuildTarget.perl.${perlVariant};
          perlOnHostForHost = override pkgsHostHost.perl.${perlVariant};
          perlOnTargetForTarget =
            if lib.hasAttr perlVariant (pkgsTargetTarget.perl or { }) then
              (override pkgsTargetTarget.perl.${perlVariant})
            else
              { };

          tests.withCheck = finalAttrs.finalPackage.overrideAttrs (_: {
            preCheck = ''
              # Weird test failure, can't even understand what it's about
              # Disable the test for now
              sed -i '/ext\/Pod-Html\/t\/htmldir3.*/d' MANIFEST
            '';
            doCheck = true;
          });
        };

      # TODO: it seems like absolute paths to some coreutils is required.
      postInstall = ''
        # Remove dependency between "out" and "man" outputs.
        rm "$out"/lib/perl5/*/*/.packlist

        # Remove dependencies on glibc and gcc
        sed "/ *libpth =>/c    libpth => ' '," \
          -i "$out"/lib/perl5/*/*/Config.pm
        # TODO: removing those paths would be cleaner than overwriting with nonsense.
        substituteInPlace "$out"/lib/perl5/*/*/Config_heavy.pl \
          --replace "${libcInc}" /no-such-path \
          --replace "${if stdenv.hasCC then stdenv.cc else "/no-such-path"}" /no-such-path \
          --replace "${
            if stdenv.hasCC && stdenv.cc.cc != null then stdenv.cc.cc else "/no-such-path"
          }" /no-such-path \
          --replace "${
            if stdenv.hasCC && stdenv.cc.fallback_sdk or null != null then
              stdenv.cc.fallback_sdk
            else
              "/no-such-path"
          }" /no-such-path \
          --replace "$man" /no-such-path
      ''
      + lib.optionalString crossCompiling ''
        mkdir -p $mini/lib/perl5/cross_perl/${version}
        for dir in cnf/{stub,cpan}; do
          cp -r $dir/* $mini/lib/perl5/cross_perl/${version}
        done

        mkdir -p $mini/bin
        install -m755 miniperl $mini/bin/perl

        export runtimeArch="$(ls $out/lib/perl5/site_perl/${version})"
        # wrapProgram should use a runtime-native SHELL by default, but
        # it actually uses a buildtime-native one. If we ever fix that,
        # we'll need to fix this to use a buildtime-native one.
        #
        # Adding the arch-specific directory is morally incorrect, as
        # miniperl can't load the native modules there. However, it can
        # (and sometimes needs to) load and run some of the pure perl
        # code there, so we add it anyway. When needed, stubs can be put
        # into $mini/lib/perl5/cross_perl/${version}.
        wrapProgram $mini/bin/perl --prefix PERL5LIB : \
          "$mini/lib/perl5/cross_perl/${version}:$out/lib/perl5/${version}:$out/lib/perl5/${version}/$runtimeArch"
      ''; # */

      meta = {
        homepage = "https://www.perl.org/";
        description = "Standard implementation of the Perl 5 programming language";
        license = lib.licenses.artistic1;

        platforms = lib.platforms.all;
        priority = 6; # in `buildEnv' (including the one inside `perl.withPackages') the library files will have priority over files in `perl`
        mainProgram = "perl";
        identifiers.cpeParts = lib.meta.cpeFullVersionWithVendor "perl" finalAttrs.version;
      };
    }
    // lib.optionalAttrs crossCompiling rec {
      crossVersion = "1.6.4";

      perl-cross-src = fetchFromGitHub {
        name = "perl-cross-${crossVersion}";
        owner = "arsv";
        repo = "perl-cross";
        rev = crossVersion;
        hash = "sha256-Qcysy7f887XHlq23iE5U92PhxDhpgaluITZBSdcc9Ck=";
      };

      patches =
        commonPatches
        # Missing d_fdopendir/HAS_FDOPENDIR: https://github.com/arsv/perl-cross/pull/159
        ++ lib.optional (lib.versionAtLeast version "5.40.0") (versionPatches + "/cross-fdopendir.patch")
        # perl-cross 1.6.4 has no 5.42.3 patch set; link the 5.42.0 one.
        ++ lib.optional (version == "5.42.3") (versionPatches + "/perl-cross-1.6.4--5.42.3.patch");

      depsBuildBuild = [
        buildPackages.stdenv.cc
        makeWrapper
      ];

      postUnpack = ''
        unpackFile ${perl-cross-src}
        chmod -R u+w ${perl-cross-src.name}
        cp -R ${perl-cross-src.name}/* perl-${version}/
      '';

      configurePlatforms = [
        "build"
        "host"
        "target"
      ];

      # TODO merge setup hooks
      setupHook = ./setup-hook-cross.sh;
    }
  );

in

self
